INSERT INTO Ingredient (name, price) VALUES
                                          ('onions', NULL),
                                          ('tomatoes', NULL),
                                          ('eggs', NULL),
                                          ('paneer', NULL),
                                          ('butter', NULL),
                                          ('cream', NULL),
                                          ('rice', NULL),
                                          ('carrots', NULL),
                                          ('peas', NULL),
                                          ('beans', NULL),
                                          ('potatoes', NULL),
                                          ('wheat flour', NULL),
                                          ('yogurt', NULL),
                                          ('gram flour', NULL),
                                          ('chickpeas', NULL),
                                          ('spinach', NULL),
                                          ('instant noodles', NULL),
                                          ('cabbage', NULL);  -- Dummy ingredient

